### PR TITLE
docs: interval datatype

### PR DESCRIPTION
**Pull request by soyeric128**
- added new datatype: Interval.
- This PR also updated the filenames of other data types to make the links a little bit shorter. For example, `20-data-type-time-date-types.md` to `datetime.md`.
- fixed the related broken links due to the filename changes.

### CODE REVIEW

**Comment by TCeason** [comment]
Please wait https://github.com/databendlabs/bendsql/pull/536 merged. Now bendsql do not support query interval type.

**Review by TCeason — APPROVED** [review]
LGTM

**Comment by BohuTANG** [comment]
> Please wait [databendlabs/bendsql#536](https://github.com/databendlabs/bendsql/pull/536) merged. Now bendsql do not support query interval type.

This PR is merged, need publish a new bendsql version or not?

**Comment by TCeason** [comment]
> > Please wait [databendlabs/bendsql#536](https://github.com/databendlabs/bendsql/pull/536) merged. Now bendsql do not support query interval type.
> 
> 
> 
> This PR is merged, need publish a new bendsql version or not?

Need publish new version.

**Pull request merged**
