### PR TITLE
feat: explain analyze graphical

### PR DESCRIPTION
**Pull request by Maricaya**
I am a student that from Open Source Promotion Plan 2024. Add `explain analyze graphical` for BendSQL.

### CODE REVIEW

**Comment by soyeric128** [comment]
```shell
MacBook-Air:Desktop eric$ bendsql
Welcome to BendSQL 0.19.2-1e338e1(2024-07-17T09:02:28.323121000Z).
Connecting to localhost:8000 as user root.
Connected to Databend Query v1.2.642-nightly-dd45c198ba(rust-1.81.0-nightly-2024-09-29T22:09:33.443401294Z)

root@localhost:8000/default> EXPLAIN ANALYZE GRAPHICAL select 1;
error: APIError: ResponseError with 1005: error:
  --> SQL:1:17
  |
1 | EXPLAIN ANALYZE GRAPHICAL select 1
  |                 ^^^^^^^^^ unexpected `GRAPHICAL`, expecting `PARTIAL`, `GRANT`, `REPLACE`, `ROLLBACK`, `DROP`, `BEGIN`, `VACUUM`, `UNDROP`, `CREATE`, `RENAME`, `IGNORE_RESULT`, `ATTACH`, `REFRESH`, `OPTIMIZE`, `EXPLAIN`, `PRESIGN`, `DESCRIBE`, `TRUNCATE`, `SHOW`, `KILL`, `DESC`, `LIST`, `COPY`, `CALL`, `FROM`, `INTERSECT`, `TABLE`, `UNION`, `ORDER`, `LIMIT`, `ALTER`, `MERGE`, `SELECT`, `VALUES`, `COMMIT`, `EXISTS`, `REMOVE`, `REVOKE`, `ANALYZE`, `EXECUTE`, `WITH`, `ABORT`, `EXCEPT`, `UPDATE`, `(`, `OFFSET`, `SET`, `SYSTEM`, `USE`, `INSERT`, `DELETE`, or `UNSET`


root@localhost:8000/default>
```

**Comment by Chasen-Zhang** [comment]
> ```shell
> MacBook-Air:Desktop eric$ bendsql
> Welcome to BendSQL 0.19.2-1e338e1(2024-07-17T09:02:28.323121000Z).
> Connecting to localhost:8000 as user root.
> Connected to Databend Query v1.2.642-nightly-dd45c198ba(rust-1.81.0-nightly-2024-09-29T22:09:33.443401294Z)
> 
> root@localhost:8000/default> EXPLAIN ANALYZE GRAPHICAL select 1;
> error: APIError: ResponseError with 1005: error:
>   --> SQL:1:17
>   |
> 1 | EXPLAIN ANALYZE GRAPHICAL select 1
>   |                 ^^^^^^^^^ unexpected `GRAPHICAL`, expecting `PARTIAL`, `GRANT`, `REPLACE`, `ROLLBACK`, `DROP`, `BEGIN`, `VACUUM`, `UNDROP`, `CREATE`, `RENAME`, `IGNORE_RESULT`, `ATTACH`, `REFRESH`, `OPTIMIZE`, `EXPLAIN`, `PRESIGN`, `DESCRIBE`, `TRUNCATE`, `SHOW`, `KILL`, `DESC`, `LIST`, `COPY`, `CALL`, `FROM`, `INTERSECT`, `TABLE`, `UNION`, `ORDER`, `LIMIT`, `ALTER`, `MERGE`, `SELECT`, `VALUES`, `COMMIT`, `EXISTS`, `REMOVE`, `REVOKE`, `ANALYZE`, `EXECUTE`, `WITH`, `ABORT`, `EXCEPT`, `UPDATE`, `(`, `OFFSET`, `SET`, `SYSTEM`, `USE`, `INSERT`, `DELETE`, or `UNSET`
> 
> 
> root@localhost:8000/default>
> ```

This feature databend has not been sent up yet, try again after a while @soyeric128

**Comment by PsiACE** [comment]
If this feature is only available in bensql, we need to mark it up in the documentation.

**Comment by Chasen-Zhang** [comment]
> If this feature is only available in bensql, we need to mark it up in the documentation.

cc @Maricaya

**Review by Chasen-Zhang — APPROVED** [review]

**Comment by soyeric128** [comment]
Please add the version this command was introduced. Example:

```
import FunctionDescription from '@site/src/components/FunctionDescription';

<FunctionDescription description="Introduced or updated: v1.2.345"/>
```

**Pull request merged**
