### PR TITLE
docs: temporary table

### PR DESCRIPTION
**Pull request by soyeric128**
- added `CREATE TEMP TABLE` cmd.
- added system table `system.temporary_tables`.
- re-organized `CREATE EXTERNAL TABLE` & `TRANSIENT TABLE`.

### CODE REVIEW

**Comment by SkyFan2002** [comment]
Need a doc for `vacuum drop table;` statement.Sometimes, temporary tables are not automatically cleaned up (e.g., if a query node crashes before the session ends). Executing this statement will help clean up any leftover files.

**Comment by SkyFan2002** [comment]
Need a doc for table function `fuse_vacuum_temporary_table()`:
```
select * from fuse_vacuum_temporary_table();
```
Sometimes, temporary tables are not automatically cleaned up (e.g., if a query node crashes before the session ends). Executing this statement will help clean up any leftover files.

**Review by SkyFan2002 — APPROVED** [review]

**Comment by SkyFan2002** [comment]
> Need a doc for table function `fuse_vacuum_temporary_table()`:
> 
> ```
> select * from fuse_vacuum_temporary_table();
> ```
> 
> Sometimes, temporary tables are not automatically cleaned up (e.g., if a query node crashes before the session ends). Executing this statement will help clean up any leftover files.

Let's merge and add this later.

**Comment by soyeric128** [comment]
> > Need a doc for table function `fuse_vacuum_temporary_table()`:
> > ```
> > select * from fuse_vacuum_temporary_table();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Sometimes, temporary tables are not automatically cleaned up (e.g., if a query node crashes before the session ends). Executing this statement will help clean up any leftover files.
> 
> Let's merge and add this later.

Sure, one question, how can i know if my temporary tables were cleaned up or not as the session ended?

**Pull request merged**
